EcommerceApp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',views.login_call),
    path('logout/',views.logout_call),
    path('signup/',views.signup),
    path('buyer/', include('buyer.urls')),
    path('seller/', include('seller.urls')),
    #path('temp/',views.temp),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buyer/urls.py
from django.urls import path
from . import views

app_name = 'buyer'


urlpatterns = [
	path('home/',views.home),
	#path('my_profile/',views.my_profile),
	path('cart/<int:id>/', views.cart, name="cart"),
	path('cartdetail/',views.cartdetails),
	path('profile/',views.profile),
	path('cartcalculate/',views.cartcalculate),
	path('cartdelete/<int:id>/',views.cartdelete, name="delpro"),
	
]

templates/CartDetails.html
{% extends 'index.html' %}


{% block navigation %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Welcome {{ request.user }}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/buyer/home/">Home
              
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/buyer/profile/">My Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Orders</a>
          </li>
          <li class="nav-item  active">
            <a class="nav-link" href="/buyer/cartdetail/">Cart<sup>{{count}}</sup></a><span class="sr-only">(current)</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

{% endblock %}




{% block mainbody %}
  <!-- Page Content -->
  <div class="container">

    <div class="row">

     
      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-12">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/1200x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/1200x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/1200x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">
          <h1>Cart Details</h1><br>
    <form method="post" action="/buyer/cartcalculate/">
      
          <table class="table table-hover">
            {%csrf_token%}
            <tr>
              <th>Product Name</th>
              <th>Product Price</th>
              <th>Quantity</th>
              <th>Remove</th>
            </tr>
            {% for i in added_product %}
            <tr>
              <td>{{i.pname}}</td>
              <td>{{i.price}}</td>
              <td><input type="number" name="productqty">
              <input type="hidden" name="price" value="{{i.price}}">
              <input type="hidden" name="pid" value="{{i.id}}">
            </td>
              <td><a href="{% url 'buyer:delpro' id=i.id %}" class="btn btn-danger">Remove</a></td>
            </tr>
            
            {% endfor %}
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td><input type="submit" name="" value="Checkout" class="btn btn-primary"></td>
            </tr>
          </table>
        </form>
          
          
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  {% endblock %}

templates/WelcomeBuyer.html
{% extends 'index.html' %}


{% block navigation %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Welcome {{ request.user }}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/buyer/home/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/buyer/profile/">My Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/buyer/cartdetail/">Cart<sup>{{count}}</sup></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

{% endblock %}




{% block mainbody %}
  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Shop Name</h1>
        {% for i in data1%}
        <div class="list-group">
          <a href="#" class="list-group-item">{{i.catname}}</a>
          
        </div>
        {% endfor %}
      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">
          {% for i in data %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="{{i.pic.url}}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">{{i.pname}}</a>
                </h4>
                <h5>{{i.price}}</h5>
                <p class="card-text">{{i.desc}}</p>
              </div>
              <div class="card-footer">
                <a href="{% url 'buyer:cart' id=i.id %}" class="btn btn-primary">Add to Cart</a>
              </div>
            </div>
          </div>

          {% endfor %}

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  {% endblock %}

templates/add_product.html
{% extends 'index.html' %}


{% block navigation %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Welcome {{ request.user }}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/seller/home/">Home
              
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/my_profile/">My Profile</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/seller/add_product/">Add Product <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">View Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

{% endblock %}

{% block mainbody %}

	<div class="container jumbotron">
		
		<h1>Add Product here!</h1>
    <div class="row">
      <div class="col-md-4">
        
      </div>
      <div class="col-md-4">
        
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <input type="text" name="pname" placeholder="Product Name" class="form-control">
              </div>
              <div class="form-group">
              <input type="text" name="price" placeholder="Product Price" class="form-control">
            </div>
            <div class="form-group">
              <input type="number" name="qty" placeholder="Product Stock" class="form-control">
            </div>
            <div class="form-group">
              <input type="text" name="desc" placeholder="Product Description" class="form-control">
            </div>
            <div class="form-group">
              <input type="file" name="pic" placeholder="Product Image" class="form-control">
            </div>
              <div class="form-group">
                <select name="category" class="form-control">
                  {% for i in cats %}
                  <option value="{{i.id}}">{{ i.catname}}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="form-group">
                <input type="submit" value="Add" class="form-control btn btn-primary">
              </div>
              <div>
                
              </div>
            
            
          </form>
          
        </div>
      </div>
      <div class="col-md-4">
        
      </div>


    </div>
	</div>


{% endblock %}

templates/buyerprofile.html
{% extends 'index.html' %}


{% block navigation %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Welcome {{ request.user }}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/buyer/home/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/buyer/profile/">My Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/buyer/cartdetail/">Cart<sup>{{count}}</sup></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

{% endblock %}




{% block mainbody %}
  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Shop Name</h1>
        
        <div class="list-group">
          <a href="#" class="list-group-item">Basic Profile</a>
          <a href="#" class="list-group-item">My Addressess</a>
          
        </div>
        
      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <input type="text" name="name" class="form-control" placeholder="Enter Name">
            </div>
            <div class="form-group">
              <input type="number" name="mobile" class="form-control" placeholder="Enter Mobile">
            </div>
            <div class="form-group">
              <input type="number" name="pincode" class="form-control" placeholder="Enter Pincode">
            </div>
            <div class="form-group">
              <input type="text" name="locality" class="form-control" placeholder="Locality">
            </div>
            <div class="form-group">
              <input type="text" name="address" class="form-control" placeholder="Address">
            </div>
            <div class="form-group">
              <input type="text" name="city" class="form-control" placeholder="City">
            </div>
            <div class="form-group">
              <input type="text" name="state" class="form-control" placeholder="State">
            </div>
            <div class="form-group">
              <input type="text" name="landmark" class="form-control" placeholder="Landmark">
            </div>
            <div class="form-group">
              <input type="submit" name="" value="Save" class="btn btn-primary">
            </div>
          </form>

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  {% endblock %}

templates/imgupload.html
<!DOCTYPE html>
<html>
<head>
	<title>Multiple Image Upload</title>
</head>
<body>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
	<input type="file" name="image" multiple>
	<input type="submit" name="" value="save">

	</form>
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Shop Homepage - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  {% block navigation %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% endblock %}

  {% block mainbody %}
  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Shop Name</h1>
        <div class="list-group">
          <a href="#" class="list-group-item">Category 1</a>
          <a href="#" class="list-group-item">Category 2</a>
          <a href="#" class="list-group-item">Category 3</a>
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item One</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item Two</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor sit amet.</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item Three</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item Four</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item Five</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor sit amet.</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item Six</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  {% endblock %}

  {% block footer %}
  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>
  {% endblock %}
  
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">	
</head>
<body>
	<div class="container jumbotron">
		<div class="row">
			<div class="col-md-4">
				
			</div>
			<div class="col-md-4">
				<h1>Login Here!</h1>
				<form method="post">
					{% csrf_token %}
					<div class="form-group">
						<input type="text" name="username" class="form-control" placeholder="UserName">
					</div>
					<div class="form-group">
						<input type="password" name="password" class="form-control" placeholder="Password">
					</div>
					<div class="form-group ">
						<input type="submit" name="login" value="Login" class="form-control btn btn-primary">
					</div>
				</form>
				
				
			</div>
			<div class="col-md-4">
				
			</div>
		</div>
	</div>

</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html>
<head>
	<title>Signup Page</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">	
</head>
<body>
	<div class="container jumbotron">
		<div class="row">
			<div class="col-md-4">
				
			</div>
			<div class="col-md-4">
				<h1>Signup Here!</h1>
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-group">
						<input type="text" name="fname" class="form-control" placeholder="First Name">
					</div>
					<div class="form-group">
						<input type="text" name="lname" class="form-control" placeholder="Last Name">
					</div>
					<div class="form-group">
						<input type="number" name="mobile" class="form-control" placeholder="Mobile">
					</div>
					<div class="form-group">
						<input type="email" name="email" class="form-control" placeholder="Email">
					</div>
					<div class="form-group">
						<input type="text" name="username" class="form-control" placeholder="UserName">
					</div>
					<div class="form-group">
						<input type="password" name="password" class="form-control" placeholder="Password">
					</div>
					<div class="form-group">
						<select class="form-control" name="role">
							<option value="buyer">Buyer</option>
							<option value="seller">Seller</option>
						</select>
					</div>
					<div class="form-group">
              			<input type="file" name="profile_pic" placeholder="Profile Image" class="form-control">
            		</div>
					<div class="form-group ">
						<input type="submit"  value="Signup" class="form-control btn btn-primary">
					</div>
					
				</form>
				
				
			</div>
			<div class="col-md-4">
				
			</div>
		</div>
	</div>

</body>
</html>

templates/welcomeSeller.html
{% extends 'index.html' %}


{% block navigation %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Welcome {{ request.user }}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/seller/home/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/my_profile/">My Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/add_product/">Add Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">View Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

{% endblock %}

{% block mainbody %}

	<div class="container jumbotron">
		<h1>Welcome {{ request.user.first_name | upper }}</h1>
		<h1>{{ data.role }}</h1>
	</div>


{% endblock %}